version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/_data/postgres:/var/lib/postgresql/data
      - ${PWD}/docker/_postgres/scripts/create_test_db.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: app
    restart: always
    command: >
        sh -c "
               python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py collectstatic --no-input &&
               python3 manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - ${PWD}/app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - django-static:/app/static
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 5050:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - django-static:/app/static
    depends_on:
      - app

  adminer:
    image: adminer
    container_name: adminer
    restart: always  
    ports:
      - 8181:8080

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  django-static:

networks:
  default: